name: workflow_02
on:
  repository_dispatch:
    types: [workflow_02]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - env:
          VERSION: ${{ github.event.client_payload.version }}
          VERSION_TYPE: ${{ github.event.client_payload.versionType }}
          BRANCH_NAME: ${{ github.event.client_payload.branchName }}
        run: |
          echo $VERSION
          echo $VERSION_TYPE
          echo $BRANCH_NAME
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.branchName }}
