name: workflow_02
on:
  workflow_dispatch:
  repository_dispatch:
    types: [workflow_02]
jobs:
  cypress-run:
    if: ${{ !github.event.client_payload.version }}
    runs-on: ubuntu-latest
    steps:
      - env:
          VERSION: ${{ github.event.client_payload.version }}
          VERSION_TYPE: ${{ github.event.client_payload.versionType }}
        run: |
          echo $VERSION
          echo $VERSION_TYPE
